const routes = {
  UpdateCertificate:'/customers/certificates/update',
  CreateCertificate:'/customers/certificates/add',
  getCandidateLists:'/customers/candidates',
  getCertificates:'/customers/certificates',
  ServiceInvoiceDetail:'/customers/services/details',
  UpdateAddOnservice:'/customers/services/update',
  getInvoices:'/customers/services',
  CreateAddOnService:'/customers/services/add',
  requestBuyerId: 'customers/requestBuyerId',
  requestBuyerIdAgain: 'customers/requestBuyerIdAgain',
  getCustomerDropDown: 'customers/dropdown',
  getCustomerQueue: '/customers',
  getCustomerDetail: 'customers/details',
  getBuyerIdDetail: 'customers/buyerId/details',
  getBuyerIdByAuctionId: 'customers/request/details',
  verifyFinance: 'customers/verifyFinance',
  allocateBuyerId: 'customers/allocateBuyerId',
  deallocateBuyerId: 'customers/deallocateBuyerId',
  changeAllocationStatus: 'customers/changeAllocationStatus',
  getMessages: 'customers/messages',
  sendMessage: 'customers/sendMessage',
  getCustomerBooking: 'customers/booking',
  getCustomerBuyerId: 'customers/buyerIds',
  deleteId:'customers/removeAuctionHouse',
  getGalaxyCustomerList:'customers/galaxy',
  CreateMemo:'customers/sendMemo',
  CreateNotifcation:'customers/sendNotifications',
  ChangeBranch:'customers/updateBranch',
  ChangeType:'customers/updateTrustedStatus',
  CreateSubCustomer:'users/addSubCustomer',
  getSubCustomerList:'users/subCustomers',
  SelectCustomer:'vehicleBookings/update',
  getAgents:'/agents',
  addCustomer:'/customers/add',
  UpdateCustomer:'customers/update',
  AddVisa:'/visas/addRequest',
  VisaProcessing:'/visas/processing',
  getWPSList:'/customers/wps',
  UpdateWPStatus:'/customers/wps/update',
  CreateWPS:'/customers/wps/add',
  UpdateAddOnService:'/customers/services/update',
  getCandidateDetail:'/customers/candidates/details',
  CustomerStatus:'customers/updateStatus',
  DeleteVoucher:'accounts/journalVouchers/delete',
  checkWPS:'/customers/wps/check',
  getRejectedVisa:'customers/candidates/rejected',
  UpdateCandidate:'customers/candidates/update',
  handleDeleteDraft:'visas/deleteDraft',
  handleDeleteCustomer:'/customers/delete',
  getCategoryList:'/services/categories',
  CreateCategory:'/services/categories/add',
  getServiceItem:"/services",
  AddServiceItem:"/services/add",
  UpdateServiceItem:"/services/update",
  DeleteServiceItem:"/services/delete",
  DetailServiceItem:"/services/details",

  getCategoryDetail:'/services/categories/details',
  UpdateCategory:'/services/categories/update',
  DeleteCategory:'',
  getReceptionDetail:'/sales/reception/details',
  getCompanies:'/customers/companies',
  addCompany:'/customers/companies/add',
  CreateReception:'/sales/reception/add',
  getReceptionsList:"/sales/reception",
  deleteReception:'/sales/reception/delete',
  UpdateReception:'/sales/reception/update',
  CreateBank:'/system/banks/add',
  getBanks:'/system/banks',
  DeleteBank:'/system/banks/delete',
  UpdateBank:'/system/banks/update',
  getBankDetail:'/system/banks/details',
  CreateSaleReceipt:'/sales/receipts/pre/add',
  getPreSales:'/sales/receipts',
  getInvoices:'/sales/receipts/paid',
  getPreSaleDetail:'/sales/receipts/details',
  DeletePreSale:'/sales/receipts/delete',
  UpdateSaleReceipt:'/sales/receipts/update',
  CreateAlDed:'/sales/receipts/place',
  getReceiptDetail:'/sales/receipts/details',
  CreateCard:'/system/cards/add',
  getCards:'/system/cards/',
  UpdateCard:'/system/cards/update',
  getInvoiceNumber:'/sales/receipts/invoiceNumber',
  getServiceReport:'/reports/serviceReport',
  getCollectionReport:'/reports/collectionReport',
  PayReceipt:'/sales/receipts/pay/v2',
  UpdateReceipt:'/sales/reception/update',
  CreditReceipt:'/sales/receipts/credit',
  getSystemSettings:'/system/settings',
  DeleteCustomerPayment:'payments/customer/delete',
  CreateCustomerPayment:'payments/customer/add'

};

export default routes